# Adding uncertainty to forecasts {#sec-second-forecast}

The forecast you generated in @sec-first-forecast included uncertainty due to future weather. As you learned in @sec-under-unc, many other sources of uncertainty could be included in your forecast. Your task is to apply the techniques in @sec-under-unc to generate additional sources of uncertainty in the forecast model from @sec-first-forecast. When you are finished, your model from @sec-first-forecast should have driver, parameter, and process uncertainty. You will submit the assignment as an updated GitHub repository with the code and plot of your forecast with all uncertainty sources included.

You will generate forecasts of water temperature at NEON Aquatics sites, with estimated uncertainty.

A [version of the template](https://github.com/frec-5174/book-problem-sets/blob/main/forecast_code_template_mod6.R) from @sec-first-forecast is provided that recodes the template to match the approach in @sec-under-unc. You should add your model from @sec-first-forecast to this template before adding the uncertainty sources from @sec-under-unc.  In the updated template, you will notice two new "for-loops" that iterate over the forecast dates and ensemble members.  These loops, while less efficient than the original code in `forecast_code_template.R`, are designed to be more explicit about the individual calculations for each ensemble member. Refactoring code this way makes it easier to transition to process-based models and models with lagged variables. 

## Reading

Thomas, R. Q., Boettiger, C., Carey, C. C., Dietze, M. C., Johnson, L. R., Kenney, M. A., et al. (2023). The NEON Ecological Forecasting Challenge. Frontiers in Ecology and the Environment, 21(3), 112–113. <https://doi.org/10.1002/fee.2616>

## Assignment

### Part 1

This chapter sets the foundation for @sec-second-forecast. In prep for @sec-second-forecast, there is a code-based version of this chapter that provides example code and introduces key concepts that will guide your work adding uncertainty to your forecast from @sec-first-forecast.

The code-based assignment will require you to create a GitHub repository with your completed code from the NEON Forecasting Challenge workshop @sec-first-forecast. You will build on this repository throughout the rest of section 1 of the book. You can learn more about setting up Git and GitHub in @sec-github.

## Reading

Dietze, M. C., Fox, A., Beck-Johnson, L. M., Betancourt, J. L., Hooten, M. B., Jarnevich, C. S., et al. (2018). Iterative near-term ecological forecasting: Needs, opportunities, and challenges. Proc Natl Acad Sci U S A, 115(7), 1424–1432. <https://doi.org/10.1073/pnas.1710231115>

## Problem set

1.  Fork [repository](https://github.com/MacrosystemsEDDIE/module6_R) for the assignment.
2.  Complete activities A, B, and C (through question 16) in the [Rmarkdown document](https://github.com/MacrosystemsEDDIE/module6_R/blob/main/assignment/module6.Rmd). You will be modifying the Rmarkdown document with the answers to the questions (both text and code).
3.  Knit the Rmarkdown Rmd to html.
4.  Commit Rmarkdown and HTML file to GitHub


Pre-assignment set up: Complete @sec-first-forecast and the RShiny version of @sec-under-unc

1. Complete the code-based version of @sec-under-unc.
2. Copy the code from [version of the template](https://github.com/frec-5174/book-problem-sets/blob/main/forecast_code_template_mod6.R) into a new R script in your GitHub repo called "forecast_code_template_mod6.R".
3. Add your model from "forecast_code_template.R" to "forecast_code_template_mod6.R".
4. Modify your "forecast_code_template.R" to include the additional sources of uncertainty
5. Run the "forecast_code_template_mod6.R" to generate a forecast, submit the forecast, and generate the plot of the forecast.
6. Update your model description at the top of "forecast_code_template_mod6.R" to describe the new sources of uncertainty.
7. Commit the updated "forecast_code_template_mod6.R" to GitHub.
8. Upload to your new plot and a link to your GitHub repository to Canvas (or other learning management system).

## Module reference

Olsson F, C. Boettiger, C.C. Carey, M. Lofton and R.Q. Thomas. 2024. Can you predict the future? A tutorial for the National Ecological Observatory Network Ecological Forecasting Challenge. Journal of Open Source Education 7: 259. https://doi.org/10.21105/jose.00259
